### ISSUE TITLE
Physics Mod Incompatibility

### ISSUE THREAD

**Issue by theelevinr** [Alexandra-Myers/Combatify#50]
When using the physics mod feature "mob physics", killing any mob causes the game to instantly crash. I have verified, that this problem only occurs due to the physics mod, and only occurs with this specific feature enabled. The issue also occurs regardless of the specific settings of the Combatify mod.

Here is the stacktrace:
```
[02:48:59] [Server thread/INFO]: [STDERR]: java.lang.Exception: Stack trace
[02:48:59] [Server thread/INFO]: [STDERR]: 	at java.base/java.lang.Thread.dumpStack(Unknown Source)
[02:48:59] [Server thread/INFO]: [STDERR]: 	at net.diebuddies.physics.PhysicsMod.getInstance(PhysicsMod.java:545)
[02:48:59] [Server thread/INFO]: [STDERR]: 	at net.diebuddies.physics.PhysicsMod.blockifyEntity(PhysicsMod.java:712)
[02:48:59] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_1309.handler$dfd000$physicsmod$onDeath(class_1309.java:12650)
[02:48:59] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_1309.method_6078(class_1309.java)
[02:48:59] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_1309.method_5643(class_1309.java:1222)
[02:48:59] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_1642.method_5643(class_1642.java:292)
[02:48:59] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_1309.method_5768(class_1309.java:277)
[02:48:59] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_3075.method_13430(class_3075.java:32)
[02:48:59] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_3075.method_13431(class_3075.java:25)
[02:48:59] [Server thread/INFO]: [STDERR]: 	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264)
[02:48:59] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_2170.redirect$coe000$architectury$performCommand(class_2170.java:1545)
[02:48:59] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_2170.method_9249(class_2170.java:287)
[02:48:59] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_3244.method_45010(class_3244.java:1341)
[02:48:59] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_3244.method_44356(class_3244.java:1321)
[02:48:59] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.method_5386(class_1255.java:67)
[02:48:59] [Server thread/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
[02:48:59] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_3738.run(class_3738.java:18)
[02:48:59] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.method_18859(class_1255.java:156)
[02:48:59] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_4093.method_18859(class_4093.java:23)
[02:48:59] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:782)
[02:48:59] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164)
[02:48:59] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.method_16075(class_1255.java:130)
[02:48:59] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:12818)
[02:48:59] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758)
[02:48:59] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.method_18857(class_1255.java:139)
[02:48:59] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:743)
[02:48:59] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675)
[02:48:59] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
[02:48:59] [Server thread/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by StunfMC** [comment]
This issue should be resolved as of 1.2.0. Please let us know if the issue still persists.
