### ISSUE TITLE
[Fabric 1.20.1] Incompatible with Immersive Paintings

### ISSUE THREAD

**Issue by joebig22** [Alexandra-Myers/Combatify#61]
Minecraft 1.20.1
Fabric Loader 0.14.22

Mods Installed:
Fabric API 0.90.0
Combatify 1.1.8.1
owo-lib 0.11.2
Immersive Paintings 0.6.7

Expected Behavior: When clicking on "New Painting", a hud would appear where you'd paste your image url and everything would work fine
Observed Behavior: When clicking on "New Painting", that hud appears but the game crashes instantly

Steps to Reproduce:
Install the mods
Enter a world
Press 'T'
Type '/give @p immersive_paintings:painting' in the chat
Get the painting item you just got
Place it somewhere
Right click it
Click "New Painting"
Game Crashes

**Comment by joebig22** [comment]
@Alexandra-Myers is this useful when it crashes it says this
```

FATAL ERROR in native method: Thread[pool-30-thread-1,5,main]: No context is current or a function that is not available in the current context was called. The JVM will abort execution.
	at org.lwjgl.opengl.GL11C.nglGenTextures(Native Method)
	at org.lwjgl.opengl.GL11C.glGenTextures(GL11C.java:667)
	at org.lwjgl.opengl.GL11.glGenTextures(GL11.java:2439)
	at com.mojang.blaze3d.platform.GlStateManager._genTexture(GlStateManager.java:562)
	at com.mojang.blaze3d.platform.TextureUtil.generateTextureId(TextureUtil.java:45)
	at net.minecraft.class_1044.method_4624(class_1044.java:41)
	at net.minecraft.class_1043.<init>(class_1043.java:28)
	at immersive_paintings.client.gui.ImmersivePaintingScreen.loadImage(ImmersivePaintingScreen.java:762)
	at immersive_paintings.client.gui.ImmersivePaintingScreen.lambda$rebuildScreenshots$52(ImmersivePaintingScreen.java:644)
	at immersive_paintings.client.gui.ImmersivePaintingScreen$$Lambda$28966/0x000000080421c658.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(java.base@17.0.7/Executors.java:539)
	at java.util.concurrent.FutureTask.run(java.base@17.0.7/FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@17.0.7/ThreadPoolExecutor.java:1136)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@17.0.7/ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(java.base@17.0.7/Thread.java:833)
```

**Comment by Alexandra-Myers** [comment]
no, not really

**Comment by Alexandra-Myers** [comment]
any other information?

**Comment by joebig22** [comment]
not really, this is the only information i have i think

immersive painting
combatify
-
place immersive painting
right click
new painting
crash

**Comment by joebig22** [comment]
Also incompatible with Signed Paintings apparently

**Comment by Alexandra-Myers** [comment]
have you tried sending logs or crash reports? small pieces of errors doesn't help, we need complete context to understand what is happening this goes for the other issue, too

**Comment by Alexandra-Myers** [comment]
... How are you using 1.1.8.2? That's not even out yet... Why is the game saying that?

**Comment by joebig22** [comment]
> ... How are you using 1.1.8.2? That's not even out yet... Why is the game saying that?

i got it from an artifact
but the same crash happens with the 1.1.8.1 version

**Comment by Alexandra-Myers** [comment]
not that it matters- I have zero clue what is happening; for some reason, the game is just dying.

**Comment by Alexandra-Myers** [comment]
I don't even touch paintings, but it seems to be a rendering bug

**Comment by Alexandra-Myers** [comment]
new artifact *might* fix it

**Comment by Alexandra-Myers** [comment]
send logs if no

**Comment by joebig22** [comment]
it's working now
thanks!!
