### ISSUE TITLE
Crash while loading into the world with custom item config (modded)

### ISSUE THREAD

**Issue by Instaplayer** [Alexandra-Myers/Combatify#64]
Game Version: 1.20.1
Mod Version: 1.1.8.3
Loader: Fabric

I am running combatify with a bunch of modded weapons (Simply Swords, Paladins & Priests to name a few)

To balance out the modpack I configured all the weapons and when I tried to launch a world, I crashed.
From my testing and the stack trace the error is related to the Defender enchantment.

When any blocking-related attribute is added to the item config, be it `damage_protection`, `blocking_type` or even `weapon_type` with `"SWORD"` value, having the Defender enchantment disabled in the main config will cause the mod to try to register it anyway despite the registry being already frozen, resulting in a crash.

Enabling Defender in the config fixes the crash.

Stack Trace:
```
[21:02:36] [Render thread/ERROR]: Unreported exception thrown!
java.lang.ExceptionInInitializerError: null
	at net.atlas.combatify.util.SwordBlockingType.getShieldBlockDamageValue(SwordBlockingType.java:50) ~[Combatify%201.20%201.1.8.3.jar:?]
	at net.minecraft.class_1799.handler$bgo000$combatify$addHoverText(class_1799.java:10628) ~[client-intermediary.jar:?]
	at net.minecraft.class_1799.method_7950(class_1799.java:650) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1591(class_310.java:850) ~[client-intermediary.jar:?]
	at java.util.stream.ReferencePipeline$7$1.accept(Unknown Source) ~[?:?]
	at java.util.Collections$2.tryAdvance(Unknown Source) ~[?:?]
	at java.util.Collections$2.forEachRemaining(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:?]
	at net.minecraft.class_7454.method_43796(class_7454.java:20) ~[client-intermediary.jar:?]
	at net.minecraft.class_1126.method_4799(class_1126.java:26) ~[client-intermediary.jar:?]
	at net.minecraft.class_1124$class_7457.method_43807(class_1124.java:61) ~[client-intermediary.jar:?]
	at net.minecraft.class_1124.method_43804(class_1124.java:42) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_43759(class_310.java:2653) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_11106(class_634.java:1444) ~[client-intermediary.jar:?]
	at net.minecraft.class_2788.method_11997(class_2788.java:32) ~[client-intermediary.jar:?]
	at net.minecraft.class_2788.method_11054(class_2788.java:14) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1175) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[1.20.1-0.15.6.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.6.jar:?]
Caused by: java.lang.IllegalStateException: Registry is already frozen (trying to add key ResourceKey[minecraft:enchantment / combatify:defender])
	at net.minecraft.class_2370.method_40274(class_2370.java:135) ~[client-intermediary.jar:?]
	at net.minecraft.class_2370.method_46744(class_2370.java:141) ~[client-intermediary.jar:?]
	at net.minecraft.class_2370.method_10272(class_2370.java:186) ~[client-intermediary.jar:?]
	at net.minecraft.class_2378.method_39197(class_2378.java:118) ~[client-intermediary.jar:?]
	at net.minecraft.class_2378.method_10230(class_2378.java:114) ~[client-intermediary.jar:?]
	at net.atlas.combatify.enchantment.EnchantmentRegistry.registerEnchant(EnchantmentRegistry.java:10) ~[Combatify%201.20%201.1.8.3.jar:?]
	at net.atlas.combatify.enchantment.DefendingEnchantment.<clinit>(DefendingEnchantment.java:14) ~[Combatify%201.20%201.1.8.3.jar:?]
	... 32 more
```

**Comment by Instaplayer** [comment]
Forgot to mention. I have sword blocking enabled in the config

**Comment by Alexandra-Myers** [comment]
This is a known issue, and it only happens if the item has configured damage protection.

**Comment by Alexandra-Myers** [comment]
Fixed
